TZ=Asia/Ho_Chi_Minh
NODE_ENV=production
REACT_APP_ADMIN_URL="https://admin-dev.mykiot.vn"
REACT_APP_GATEWAY_API=https://gateway-dev.mykiot.vn
REACT_APP_AUTH_API=https://open-api-dev.mykiot.vn
REACT_APP_THEME_IFRAME=https://theme-dev.mykiot.vn
REACT_APP_SOCKET_IO=https://socket-dev.mykiot.vn
REACT_APP_FIREBASE_API_KEY=AIzaSyC0yWIAFaAumJHzrWNuNICn0vOz6tkpnKo
REACT_APP_FIREBASE_AUTH_DOMAIN=dev-mykiot.firebaseapp.com
REACT_APP_FIREBASE_PROJECT_ID=dev-mykiot
REACT_APP_FIREBASE_STORAGE_BUCKET=dev-mykiot.appspot.com
REACT_APP_FIREBASE_MESSAGING_SENDER_ID=507540522019
REACT_APP_FIREBASE_APP_ID=1:507540522019:web:5be875de7f77485b85dd96
REACT_APP_FIREBASE_MEASUREMENT_ID=G-JF2P9XVHP0
REACT_APP_FIREBASE_FNB_API_KEY=AIzaSyC0yWIAFaAumJHzrWNuNICn0vOz6tkpnKo
REACT_APP_FIREBASE_FNB_AUTH_DOMAIN=dev-mykiot.firebaseapp.com
REACT_APP_FIREBASE_FNB_PROJECT_ID=dev-mykiot
REACT_APP_FIREBASE_FNB_STORAGE_BUCKET=dev-mykiot.appspot.com
REACT_APP_FIREBASE_FNB_MESSAGING_SENDER_ID=507540522019
REACT_APP_FIREBASE_FNB_APP_ID=1:507540522019:web:5be875de7f77485b85dd96
REACT_APP_FIREBASE_FNB_MEASUREMENT_ID=G-JF2P9XVHP0

REACT_APP_FIREBASE_RETAIL_API_KEY=AIzaSyC0yWIAFaAumJHzrWNuNICn0vOz6tkpnKo
REACT_APP_FIREBASE_RETAIL_AUTH_DOMAIN=dev-mykiot.firebaseapp.com
REACT_APP_FIREBASE_RETAIL_PROJECT_ID=dev-mykiot
REACT_APP_FIREBASE_RETAIL_STORAGE_BUCKET=dev-mykiot.appspot.com
REACT_APP_FIREBASE_RETAIL_MESSAGING_SENDER_ID=507540522019
REACT_APP_FIREBASE_RETAIL_APP_ID=1:507540522019:web:5be875de7f77485b85dd96
REACT_APP_FIREBASE_RETAIL_MEASUREMENT_ID=G-JF2P9XVHP0

REACT_APP_FIREBASE_KIOTONLINE_API_KEY=AIzaSyC0yWIAFaAumJHzrWNuNICn0vOz6tkpnKo
REACT_APP_FIREBASE_KIOTONLINE_AUTH_DOMAIN=dev-mykiot.firebaseapp.com
REACT_APP_FIREBASE_KIOTONLINE_PROJECT_ID=dev-mykiot
REACT_APP_FIREBASE_KIOTONLINE_STORAGE_BUCKET=dev-mykiot.appspot.com
REACT_APP_FIREBASE_KIOTONLINE_MESSAGING_SENDER_ID=507540522019
REACT_APP_FIREBASE_KIOTONLINE_APP_ID=1:507540522019:web:5be875de7f77485b85dd96
REACT_APP_FIREBASE_KIOTONLINE_MEASUREMENT_ID=G-JF2P9XVHP0
REACT_APP_QR_CODE=https://qr-code-dev.mykiot.vn
REACT_APP_ASSETS_URL=https://assets-dev.mykiot.vn
