apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"consul-server","app.kubernetes.io/name":"consul-server","component":"server"},"name":"consul-server","namespace":"kube-system"},"spec":{"clusterIP":"None","ports":[{"name":"http","port":8500,"protocol":"TCP","targetPort":8500},{"name":"dns","port":8600,"protocol":"UDP","targetPort":8600}],"publishNotReadyAddresses":true,"selector":{"app.kubernetes.io/instance":"consul-server","app.kubernetes.io/name":"consul-server","component":"server"}}}
  creationTimestamp: "2023-01-30T07:54:41Z"
  labels:
    app.kubernetes.io/instance: consul-server
    app.kubernetes.io/name: consul-server
    component: server
  name: consul-server
  namespace: kube-system
  resourceVersion: "15696"
  uid: 5e808a9d-1f44-4666-b889-da203ff98410
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8500
    protocol: TCP
    targetPort: 8500
  - name: dns
    port: 8600
    protocol: UDP
    targetPort: 8600
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: consul-server
    app.kubernetes.io/name: consul-server
    component: server
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
