{{- if or .Values.runners.imagePullSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  labels:
    app: {{ include "gitlab-runner.fullname" . }}
    chart: {{ include "gitlab-runner.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuY2l0aWdvLmNvbS52biI6eyJ1c2VybmFtZSI6Imtpb3Rwcm8iLCJwYXNzd29yZCI6IkdzcGUwRlF5OHkiLCJhdXRoIjoiYTJsdmRIQnlienBIYzNCbE1FWlJlVGg1In19fQ==
{{- end -}}
