{{- if .Values.runners.serviceAccountName -}}
{{- $fullName := include "gitlab-runner.fullname" . -}}
{{- $chart := include "gitlab-runner.chart" . -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service  -}}
{{- $runnersServiceAccount := .Values.runners.serviceAccountName -}}
{{- range .Values.runners.namespace -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $runnersServiceAccount }}
  labels:
    app: {{ $fullName }}
    chart: {{ $chart }}
    release: {{ $releaseName }}
    heritage: {{ $releaseService }}
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: {{ $runnersServiceAccount }}
  namespace: {{ $releaseName }}
---
{{- end -}}
{{- end -}}
