{{- if .Values.runners.serviceAccountName -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- range $key, $value := .Values.rbac.serviceAccountAnnotations }}
    {{   $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ .Values.runners.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "gitlab-runner.fullname" . }}
    chart: {{ include "gitlab-runner.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.rbac.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.rbac.imagePullSecrets }}
  - name: {{ . | quote }}
  {{- end }}
{{- end }}
{{- end -}}
