NODE_ENV=production
REACT_APP_ADMIN_URL="https://admin-staging.mykiot.vn"
REACT_APP_GATEWAY_API=https://gateway-staging.mykiot.vn
REACT_APP_AUTH_API=https://open-api-staging.mykiot.vn
REACT_APP_THEME_IFRAME=https://theme-staging.mykiot.vn
REACT_APP_SOCKET_IO=https://socket-staging.mykiot.vn
REACT_APP_FIREBASE_API_KEY=AIzaSyAF8AYkp9Gf9au4HhiRp8QmDiX1xq_ohPk
REACT_APP_FIREBASE_AUTH_DOMAIN=staging-mykiot.firebaseapp.com
REACT_APP_FIREBASE_PROJECT_ID=staging-mykiot
REACT_APP_FIREBASE_STORAGE_BUCKET=staging-mykiot.appspot.com
REACT_APP_FIREBASE_MESSAGING_SENDER_ID=409164630446
REACT_APP_FIREBASE_APP_ID=1:409164630446:web:0033e293f6a5c4f4c5203f
REACT_APP_FIREBASE_MEASUREMENT_ID=G-Y6ZVQ42RVE
REACT_APP_QR_CODE=https://qr-code-staging.mykiot.vn
REACT_APP_FIREBASE_FNB_API_KEY=AIzaSyCh3B5xQYvLlhSGU3lvU9D28DydKRnaa3Q
REACT_APP_FIREBASE_FNB_AUTH_DOMAIN=mykiot-fnb.firebaseapp.com
REACT_APP_FIREBASE_FNB_PROJECT_ID=mykiot-fnb
REACT_APP_FIREBASE_FNB_STORAGE_BUCKET=mykiot-fnb.appspot.com
REACT_APP_FIREBASE_FNB_MESSAGING_SENDER_ID=664411204368
REACT_APP_FIREBASE_FNB_APP_ID=1:664411204368:web:0b78b47e566bba9d901395
REACT_APP_FIREBASE_FNB_MEASUREMENT_ID=G-TE2FM7THPC

REACT_APP_FIREBASE_RETAIL_API_KEY=AIzaSyDLwO0uUUrqfzeucajsgqzA4gqsj65Fv5Q
REACT_APP_FIREBASE_RETAIL_AUTH_DOMAIN=mykiot-retail.firebaseapp.com
REACT_APP_FIREBASE_RETAIL_PROJECT_ID=mykiot-retail
REACT_APP_FIREBASE_RETAIL_STORAGE_BUCKET=mykiot-retail.appspot.com
REACT_APP_FIREBASE_RETAIL_MESSAGING_SENDER_ID=921678884073
REACT_APP_FIREBASE_RETAIL_APP_ID=1:921678884073:web:e0744f2f2dcf73486a9478
REACT_APP_FIREBASE_RETAIL_MEASUREMENT_ID=G-M4JPF6VQ9S

REACT_APP_FIREBASE_KIOTONLINE_API_KEY=AIzaSyAnnsXfNzcX13ylkRABNb-cMQ86Aa9cz-U
REACT_APP_FIREBASE_KIOTONLINE_AUTH_DOMAIN=mykiot-kiot-online.firebaseapp.com
REACT_APP_FIREBASE_KIOTONLINE_PROJECT_ID=mykiot-kiot-online
REACT_APP_FIREBASE_KIOTONLINE_STORAGE_BUCKET=mykiot-kiot-online.appspot.com
REACT_APP_FIREBASE_KIOTONLINE_MESSAGING_SENDER_ID=175057658940
REACT_APP_FIREBASE_KIOTONLINE_APP_ID=1:175057658940:web:87e9f0c6ebda35bdd38f39
REACT_APP_FIREBASE_KIOTONLINE_MEASUREMENT_ID=G-PYL9HFNX9L
REACT_APP_ASSETS_URL=https://assets-staging.mykiot.vn
REACT_APP_KIOTVIET_DOMAIN=kvpos.com:59903